name: Sync SFTP Data to GitHub

on:
  workflow_dispatch: # Allows manual execution

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install lftp (for SFTP)
        run: sudo apt-get install -y lftp

      - name: Fetch Data from SFTP
        run: |
          lftp -e "
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          open sftp://${{ secrets.SFTP_USER }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_HOST }}
          mirror --verbose ${{ secrets.SFTP_PATH }} ./data 
          bye
          " > output

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated SFTP sync - $(date)"
          git push
